version: "2.1"

services:
  mediamtx:
    build: media
    restart: always
    ports:
      - 8554:8554
    devices:
      - /dev/video0:/dev/video0    # webcam
      - /dev/video11:/dev/video11  # bcm2835-codec-encode (H.264 HW encoder)
      - /dev/video12:/dev/video12  # bcm2835-codec-isp (format conversion)
    group_add:
      - video
    environment:
      - TZ=Asia/Kolkata
      - UDEV=1

  # https://github.com/balenablocks/hostname
  hostname:
    build: hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: stairs








